apiVersion: v1
kind: Service
metadata:
  name: charity-db
spec:
  selector:
    app: charity-db
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP
---

apiVersion: v1
kind: Service
metadata:
  name: charity-hub
spec:
  selector:
    app: charity-hub
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer